name: Build LaTeX
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: .
      FILE: main

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Build LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}.tex
          working_directory: ${{ env.DIR }}

      - name: Prepare artifacts
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts