on:
  push:
    branches:
      - main
    paths:
      - '**.tex'
      - 'template/**.sty'
      - 'resources/**.png'
  pull_request:
    branches:
      - main
    paths:
      - '**.tex'
      - 'template/**.sty'
      - 'resources/**.png'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build LaTeX
        run: |
          mkdir -p output
          latexmk -pdf -output-directory=output main.tex

      - name: Upload PDF (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: output/main.pdf

      - name: Upload for Pages deployment
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

      - name: Discord notification on failure
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "❌ Échec de la génération du CV !"}' \
          $DISCORD_WEBHOOK

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "📄 Nouveau CV généré avec succès ! [Lien direct](${{ steps.deployment.outputs.page_url }}main.pdf)"}' \
          $DISCORD_WEBHOOK