name: Build LaTeX
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest-basic

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            latexmk \
            texlive-lang-french \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-extra \
            texlive-xetex \
            fonts-lmodern \
            ghostscript

      - name: Build LaTeX
        run: |
          latexmk -pdf main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: main.pdf