on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build LaTeX
        run: |
          mkdir -p output
          latexmk -pdf -output-directory=output main.tex

      - name: Upload PDF (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: output/main.pdf

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
        with:
          folder: output

      - name: Notify Discord
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "📄 Nouveau CV généré avec succès ! [Lien direct](https://<ton-username>.github.io/<nom-du-projet>/main.pdf)"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

