on:
  pull_request:
    branches:
      - main
    paths:
      - 'cv/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build LaTeX
        working-directory: cv
        run: |
          mkdir -p output
          latexmk -pdf -output-directory=output main.tex

      - name: Upload PDF (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: cv/output/main.pdf

      - name: Discord notification
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "❌ Échec de la génération du CV !"}' \
          $DISCORD_WEBHOOK